import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { appSource } from "./helpers/app-source.mjs";

const html = appSource;
const css = readFileSync(new URL("../styles.css", import.meta.url), "utf8");
const storage = readFileSync(new URL("../assets/app/storage.js", import.meta.url), "utf8");
const sync = readFileSync(new URL("../assets/app/sync.js", import.meta.url), "utf8");
const historyStore = readFileSync(new URL("../assets/app/history-store.js", import.meta.url), "utf8");
const types = readFileSync(new URL("../supabase/functions/_shared/types.ts", import.meta.url), "utf8");
const reading = readFileSync(new URL("../supabase/functions/reading/index.ts", import.meta.url), "utf8");
const modelRouter = readFileSync(new URL("../supabase/functions/_shared/model-router.ts", import.meta.url), "utf8");
const weeklyPrompt = readFileSync(new URL("../supabase/functions/_shared/prompts/weekly-summary.ts", import.meta.url), "utf8");
const tokenValidator = readFileSync(new URL("../supabase/functions/_shared/token-validator.ts", import.meta.url), "utf8");

assert.match(storage, /normalizeHistoryRecord/, "storage delegates record normalization to history-store");
assert.match(sync, /historyRecordToRow[\s\S]*from "\.\/history-store\.js"/, "sync imports history row mapping from history-store");
assert.match(historyStore, /actionStatus: normalizeActionStatus\(record\.actionStatus\)/, "history store normalizes optional actionStatus");
assert.match(historyStore, /\["done", "not_done", "skipped", "not_fit"\]/, "history store supports the Phase 3 action status values");
assert.match(historyStore, /action_status: record\.actionStatus \|\| ""/, "history store writes action status to Supabase rows");
assert.match(historyStore, /actionStatus: row\.action_status \|\| ""/, "history store restores action status from Supabase rows");
assert.match(historyStore, /reviewAt: stringValue\(record\.reviewAt\)/, "history store preserves optional reviewAt");
assert.match(historyStore, /reviewNote: stringValue\(record\.reviewNote\)/, "history store preserves optional reviewNote");
assert.match(historyStore, /review_at: record\.reviewAt \|\| null/, "history store writes reviewAt to Supabase rows");
assert.match(historyStore, /review_note: record\.reviewNote \|\| ""/, "history store writes reviewNote to Supabase rows");
assert.match(historyStore, /reviewAt: row\.review_at \|\| ""/, "history store restores reviewAt from Supabase rows");
assert.match(historyStore, /reviewNote: row\.review_note \|\| ""/, "history store restores reviewNote from Supabase rows");
assert.match(historyStore, /favorite: Boolean\(record\.favorite\)/, "history store preserves optional favorite flag");
assert.match(historyStore, /is_favorite: Boolean\(record\.favorite\)/, "history store writes favorite flag to Supabase rows");
assert.match(historyStore, /favorite: Boolean\(row\.is_favorite\)/, "history store restores favorite flag from Supabase rows");

assert.match(html, /id="action-status"/, "result detail renders action status controls");
assert.equal((html.match(/data-action-status=/g) || []).length, 4, "result detail exposes four action status values");
assert.match(html, /function saveActionStatus\(status\)/, "front-end has action status save function");
assert.match(html, /saveHistoryRecord\(recordStore, record\);[\s\S]*syncAfterSave\(record\);[\s\S]*renderHistoryList\(\);/, "action status save persists locally, syncs, and refreshes history");
assert.match(html, /els\.actionStatus\.addEventListener\("click"[\s\S]*saveActionStatus\(button\.dataset\.actionStatus\);/, "action status controls save on click");
assert.match(html, /actionStatusLabel\(record\.actionStatus\)/, "history list includes action status label");
assert.match(html, /updateActionStatusUi\(record\.actionStatus \|\| ""\)/, "new records reset the selected action status");
assert.match(html, /updateActionStatusUi\(lastRecord\?\.actionStatus \|\| ""\)/, "stored records restore selected action status");
assert.match(html, /reviewAt: reviewDateAfter\(createdAt\)/, "new records get a suggested review date");
assert.match(html, /function reviewDateAfter\(value, days = 3\)/, "review date helper defaults to three days");
assert.match(html, /function isReviewDue\(record, now = new Date\(\)\)/, "review due helper checks current time");
assert.match(html, /const shouldShow = Boolean\(record\?\.reviewNote\) \|\| isReviewDue\(record\);/, "review UI appears only when due or already saved");
assert.match(html, /function saveReviewNote\(\)/, "front-end has review note save function");
assert.match(html, /reviewNote: note,[\s\S]*updatedAt[\s\S]*saveHistoryRecord\(recordStore, record\);[\s\S]*syncAfterSave\(record\);[\s\S]*renderHistoryList\(\);/, "review note persists locally, syncs, and refreshes history");
assert.match(html, /isReviewDue\(record\) && !record\.reviewNote \? t\("reviewLabel"\) : ""/, "history list flags due reviews");
assert.match(html, /els\.reviewSave\.addEventListener\("click", saveReviewNote\);/, "review save button persists the note");
assert.doesNotMatch(html, /Notification|PushManager|serviceWorker\.register/, "three-day review does not add push reminders");
assert.match(html, /id="history-filters"/, "history drawer has mode filters");
assert.equal((html.match(/data-history-filter=/g) || []).length, 4, "history drawer keeps the four useful observation filters");
assert.doesNotMatch(html, /data-history-filter="daily"/, "daily anchors no longer occupy a history filter");
assert.match(html, /function groupHistoryByDate\(records\)/, "history records are grouped by date");
assert.match(html, /function toggleHistoryFavorite\(id\)/, "history has a favorite toggle");
assert.match(html, /saveHistoryRecord\(recordStore, updated\);[\s\S]*syncAfterSave\(updated\);[\s\S]*renderHistoryList\(\);/, "favorite toggle persists locally, syncs, and refreshes history");
assert.match(html, /dataset\.historyFavorite/, "history favorite button is separate from opening a record");
assert.match(html, /record\.followups[\s\S]*t\("historyFollowupCount"\)/, "history summary shows follow-up count");
assert.match(html, /record\.clarificationOf \? t\("historyClarification"\) : ""/, "history summary shows clarification relationship");

assert.match(css, /\.action-status \{[\s\S]*display: grid;/, "action status has compact result styling");
assert.match(css, /@media \(max-width: 620px\) \{[\s\S]*\.action-status > div \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/, "action status controls fit on mobile");
assert.match(css, /\.review-box \{[\s\S]*display: grid;/, "review box has compact result styling");
assert.match(css, /\.history-filters \{[\s\S]*flex-wrap: wrap;/, "history filters wrap inside compact drawer");
assert.match(css, /\.history-row \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto;/, "history row preserves compact drawer layout");

assert.match(types, /mode: "weekly-summary"/, "weekly summary has a backend request type");
assert.match(types, /records: WeeklySummaryRecord\[\]/, "weekly summary request carries recent record summaries");
assert.match(modelRouter, /weekly: 1000/, "weekly summary has its own token cap");
assert.match(reading, /o\.mode === "weekly-summary"[\s\S]*o\.records\.length >= 3/, "weekly summary rejects insufficient records");
assert.match(reading, /case "weekly-summary":[\s\S]*buildWeeklySummaryPrompt/, "reading function routes weekly summary to its prompt");
assert.match(tokenValidator, /"weekly-summary": \["THEME", "STUCK_POINT", "NEXT_ACTION"\]/, "weekly summary has token validation");
assert.match(html, /id="weekly-summary-btn"/, "history drawer exposes weekly summary action");
assert.match(html, /function weeklySummaryRecords\(records = loadHistory\(recordStore\)\)/, "front-end builds compact weekly summary records");
const weeklyFunction = html.match(/function weeklySummaryRecords[\s\S]*?\n      function updateWeeklySummaryUi/)?.[0] || "";
assert.match(weeklyFunction, /summary: summary\.slice\(0, 220\)/, "weekly payload includes compact summaries");
assert.match(weeklyFunction, /action: action\.slice\(0, 160\)/, "weekly payload includes compact actions");
assert.doesNotMatch(weeklyFunction, /answer: record\.answer/, "weekly payload does not send full answer text");
assert.match(html, /records\.length < 3[\s\S]*return;/, "front-end does not call weekly summary below three usable records");
assert.match(html, /mode:\s*"weekly-summary"[\s\S]*entry:\s*"weekly"[\s\S]*records,/, "front-end submits weekly summary with weekly route hint");
assert.match(html, /weeklySummaryResult\.textContent = cleanTaggedOutputText\(text, "", \{[\s\S]*THEME[\s\S]*STUCK_POINT[\s\S]*NEXT_ACTION/, "weekly summary streaming strips protocol tags before display");
assert.match(html, /weeklySummaryResult\.textContent = cleanTaggedOutputText\(full, t\("weeklySummaryFailed"\), \{[\s\S]*THEME[\s\S]*STUCK_POINT[\s\S]*NEXT_ACTION/, "weekly summary final display strips protocol tags");
assert.match(weeklyPrompt, /\[THEME\]/, "weekly prompt asks for repeated theme");
assert.match(weeklyPrompt, /\[STUCK_POINT\]/, "weekly prompt asks for stuck point");
assert.match(weeklyPrompt, /\[NEXT_ACTION\]/, "weekly prompt asks for one next action");
assert.match(weeklyPrompt, /Do not predict the future|不预测未来/, "weekly prompt forbids prediction");
assert.match(weeklyPrompt, /fatalistic language|宿命化语言/, "weekly prompt forbids fatalistic language");
assert.match(weeklyPrompt, /命中注定、一定、注定、转运、改运、玄学、算命|fated/, "weekly prompt bans deterministic/fate wording");

console.log("phase3 retention contract passed");
